"""Build identity — which source revision produced this engine.

``__version__`` alone cannot tell two 0.3.0 bundles apart, so the packaged
probe could pass on any Parker.app that happened to exist. Three sources,
in order of trust:

1. ``app._build_info`` — generated by ``make sidecar`` (``write_build_info``)
   right before PyInstaller runs, so the bundle carries the SHA it was
   built from (``-dirty`` when the tree had uncommitted changes).
2. ``git rev-parse HEAD`` in a repo checkout — dev servers report the
   live tree. Never from a frozen binary: a bundle has no repo and must
   not shell out on every ``/health``.
3. ``"unknown"`` — a tarball build without git. Honest, and the probe
   fails its SHA check by design.
"""

from __future__ import annotations

import functools
import subprocess
import sys
from datetime import datetime, timezone
from pathlib import Path

from app import __version__

_GIT_TIMEOUT_SECONDS = 2.0
UNKNOWN = "unknown"


def is_frozen() -> bool:
    return bool(getattr(sys, "frozen", False))


def _stamped_sha() -> str | None:
    try:
        from app import _build_info  # type: ignore[attr-defined]  # generated, gitignored
    except ImportError:
        return None
    return getattr(_build_info, "GIT_SHA", None) or None


def _checkout_sha(repo: Path) -> str | None:
    try:
        head = subprocess.run(
            ["git", "rev-parse", "HEAD"], cwd=repo, capture_output=True, text=True,
            timeout=_GIT_TIMEOUT_SECONDS, check=False,
        )
        if head.returncode != 0 or not head.stdout.strip():
            return None
        sha = head.stdout.strip()
        status = subprocess.run(
            ["git", "status", "--porcelain"], cwd=repo, capture_output=True, text=True,
            timeout=_GIT_TIMEOUT_SECONDS, check=False,
        )
        if status.returncode == 0 and status.stdout.strip():
            sha += "-dirty"
        return sha
    except (OSError, subprocess.SubprocessError):
        return None


def git_sha() -> str:
    """The revision this process runs from: stamped in a bundle, live in a
    checkout, ``unknown`` otherwise. A frozen binary never shells out."""

    if is_frozen():
        return _stamped_sha() or UNKNOWN
    repo = Path(__file__).resolve().parents[2]
    return _checkout_sha(repo) or _stamped_sha() or UNKNOWN


@functools.lru_cache(maxsize=None)
def build_identity() -> dict:
    """``{version, git_sha, frozen}`` — resolved once per process (the
    source of a running process does not change under it)."""

    return {"version": __version__, "git_sha": git_sha(), "frozen": is_frozen()}


def write_build_info(target: Path) -> Path:
    """Generate ``app/_build_info.py`` for ``make sidecar``. PyInstaller's
    ``collect_submodules("app")`` bundles it with no spec change."""

    built_at = datetime.now(timezone.utc).strftime("%Y-%m-%dT%H:%M:%SZ")
    target.write_text(
        '"""Generated by `make sidecar` — do not edit, do not commit."""\n\n'
        f'GIT_SHA = "{git_sha()}"\n'
        f'BUILT_AT = "{built_at}"\n'
    )
    return target
